name: app_features_venue
description: "This package provides venue-related features for the application."
publish_to: "none"
version: 0.0.1
homepage: "https://github.com/FlutterKaigi/2024/tree/main/packages/app/features/venue"

environment:
  sdk: ^3.6.0-216.1.beta
  flutter: ^3.26.0-0.1.pre

dependencies:
  app_cores_core:
    path: ../../cores/core
  app_cores_designsystem:
    path: ../../cores/designsystem
  app_cores_settings:
    path: ../../cores/settings
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/

flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true
