name: ticket_api
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0-216.1.beta

dependencies:
  common_data:
    path: ../data
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  retrofit: ^4.4.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
