policy:
  - template: ["task_for_contributor.yaml", "task_for_staff.yaml"]
    section:
      - id: ["related"]
        block-list: []
        label:
          - name: "related/app"
            keys: ["App"]
          - name: "related/data"
            keys: ["Data"]
          - name: "related/ticket"
            keys: ["Ticket"]
          - name: "related/website"
            keys: ["Website"]
      - id: [type]
        block-list: []
        label:
          - name: "type/bug"
            keys: ["Bug"]
          - name: "type/feature"
            keys: ["Feature"]
          - name: "related/improvement"
            keys: ["Improvement"]
