name: conference_2024

sdkPath: .fvm/flutter_sdk

command:
  bootstrap:
    environment:
      sdk: ^3.5.0-293.0.dev
      flutter: ^3.23.0-13.0.pre
    dependencies:
      accessibility_tools: ^2.2.1
      collection: ^1.18.0
      dynamic_color: ^1.7.0
      flutter:
        sdk: flutter
      flutter_hooks: ^0.20.5
      flutter_localizations:
        sdk: flutter
      freezed_annotation: ^2.4.4
      go_router: ^14.1.4
      hooks_riverpod: ^2.5.1
      json_annotation: ^4.9.0
      riverpod_annotation: ^2.3.5
      supabase_flutter: ^2.5.8
      intl: ^0.19.0
      theme_tailor_annotation: ^3.0.1
      vector_graphics: ^1.1.11+1
    dev_dependencies:
      build_runner: ^2.4.11
      custom_lint: ^0.6.5
      flutter_test:
        sdk: flutter
      freezed: ^2.5.7
      go_router_builder: ^2.7.0
      json_serializable: ^6.8.0
      riverpod_generator: ^2.4.2
      riverpod_lint: ^2.3.13
      theme_tailor: ^3.0.1
      vector_graphics_compiler: ^1.1.11+1

packages:
  - apps/*
  - packages/**

scripts:
  custom_lint:
    exec: dart run custom_lint
    packageFilters:
      dependsOn: custom_lint

  rebuild:
    run: dart run build_runner build -d
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: build_runner

  gen-l10n:
    run: flutter gen-l10n
    exec:
      concurrency: 1
      orderDependents: true
    packageFilters:
      dependsOn: flutter_localizations
      ignore:
        - conference_2024_website
  flutter_test:
    exec: flutter test
    packageFilters:
      dependsOn: flutter_test

ide:
  intellij:
    # Disabling IntelliJ's automatic configuration.
    # This is to support different build configurations for environments.
    enabled: false
