name: conference_2024

sdkPath: .fvm/flutter_sdk

command:
  bootstrap:
    environment:
      sdk: ^3.5.0-191.0.dev
      flutter: ^3.23.0-9.0.pre
    dependencies:
      collection: ^1.18.0
      flutter:
        sdk: flutter
      flutter_hooks: ^0.20.5
      freezed_annotation: ^2.4.1
      go_router: ^14.1.4
      hooks_riverpod: ^2.5.1
      intl: ^0.19.0
      theme_tailor_annotation: ^3.0.1
      vector_graphics: ^1.1.11+1
    dev_dependencies:
      build_runner: ^2.4.11
      flutter_test:
        sdk: flutter
      freezed: ^2.5.2
      go_router_builder: ^2.7.0
      theme_tailor: ^3.0.1
      vector_graphics_compiler: ^1.1.11+1

packages:
  - apps/*
  - packages/**

ide:
  intellij:
    # Disabling IntelliJ's automatic configuration.
    # This is to support different build configurations for environments.
    enabled: false
