name: conference_2024

sdkPath: .fvm/flutter_sdk

command:
  bootstrap:
    environment:
      sdk: ^3.5.0-191.0.dev
      flutter: ^3.23.0-9.0.pre

packages:
  - apps/*
  - packages/**

ide:
  intellij:
    # Disabling IntelliJ's automatic configuration.
    # This is to support different build configurations for environments.
    enabled: false
