name: conference_2024

sdkPath: .fvm/flutter_sdk

command:
  bootstrap:
    environment:
      sdk: ^3.5.0-191.0.dev
      flutter: ^3.23.0-9.0.pre
    dependencies:
      collection: ^1.18.0
      flutter:
        sdk: flutter
      flutter_hooks: ^0.20.5
      freezed_annotation: ^2.4.1
      go_router: ^14.1.4
      hooks_riverpod: ^2.5.1
      riverpod_annotation: ^2.3.5
      intl: ^0.19.0
      theme_tailor_annotation: ^3.0.1
      vector_graphics: ^1.1.11+1
    dev_dependencies:
      build_runner: ^2.4.11
      custom_lint: ^0.6.4
      flutter_test:
        sdk: flutter
      freezed: ^2.5.2
      go_router_builder: ^2.7.0
      riverpod_generator: ^2.4.2
      riverpod_lint: ^2.3.12
      theme_tailor: ^3.0.1
      vector_graphics_compiler: ^1.1.11+1

packages:
  - apps/*
  - packages/**

scripts:
  custom_lint:
    exec: fvm dart run custom_lint
    packageFilters:
      dependsOn: custom_lint

ide:
  intellij:
    # Disabling IntelliJ's automatic configuration.
    # This is to support different build configurations for environments.
    enabled: false
