name: conference_2024

sdkPath: .fvm/flutter_sdk

command:
  bootstrap:
    environment:
      sdk: ^3.6.0-216.1.beta
      flutter: ^3.26.0-0.1.pre
    dependencies:
      accessibility_tools: ^2.2.2
      collection: ^1.19.0
      dynamic_color: ^1.7.0
      flutter:
        sdk: flutter
      flutter_hooks: ^0.20.5
      flutter_localizations:
        sdk: flutter
      flutter_markdown: ^0.7.4+1
      freezed_annotation: ^2.4.4
      go_router: ^14.2.7
      riverpod: ^2.6.1
      hooks_riverpod: ^2.6.1
      json_annotation: ^4.9.0
      package_info_plus: ^8.0.0
      riverpod_annotation: ^2.3.5
      supabase_flutter: ^2.6.0
      intl: ^0.19.0
      theme_tailor_annotation: ^3.0.1
      vector_graphics: ^1.1.11+1
    dev_dependencies:
      build_runner: ^2.4.12
      custom_lint: ^0.6.7
      flutter_test:
        sdk: flutter
      freezed: ^2.5.7
      go_router_builder: ^2.7.0
      json_serializable: ^6.8.0
      riverpod_generator: ^2.6.1
      riverpod_lint: ^2.6.1
      theme_tailor: ^3.0.1
      vector_graphics_compiler: ^1.1.11+1

packages:
  - apps/*
  - packages/**

scripts:
  custom_lint:
    run: dart run custom_lint
    exec:
      concurrency: 5
    packageFilters:
      dependsOn: custom_lint

  rebuild:
    run: dart run build_runner build -d && melos format -c 5
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: build_runner

  gen-l10n:
    run: flutter gen-l10n
    exec:
      concurrency: 1
      orderDependents: true
    packageFilters:
      dependsOn: flutter_localizations
      ignore:
        - conference_2024_website
  flutter_test:
    exec: flutter test
    packageFilters:
      dependsOn: flutter_test
  app:build:appbundle:production:
    exec: flutter build appbundle --dart-define-from-file=defines/production.env
    packageFilters:
      scope: conference_2024_app

ide:
  intellij:
    # Disabling IntelliJ's automatic configuration.
    # This is to support different build configurations for environments.
    enabled: false
