CREATE TYPE SNS_TYPE AS ENUM ('discord', 'github', 'note', 'qiita', 'x', 'zenn');

CREATE TABLE IF NOT EXISTS sns_accounts (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sns_type SNS_TYPE NOT NULL,
  account_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS staffs (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  avatar_url TEXT NOT NULL,
  introduction TEXT NOT NULL,
  sns_account_ids BIGINT[] NOT NULL
);

ALTER TABLE staffs 
    ALTER COLUMN sns_account_ids SET DEFAULT ARRAY[]::BIGINT[];

CREATE VIEW staff_with_sns_accounts AS
SELECT
    staffs.id,
    staffs.name,
    staffs.avatar_url,
    staffs.introduction,
    (
        SELECT
            json_agg(sns_accounts ORDER BY sns_account_ids.i)
        FROM
            unnest(staffs.sns_account_ids) WITH ORDINALITY AS sns_account_ids(id, i)
        JOIN sns_accounts USING (id)
    ) AS sns_accounts
FROM
    staffs;
