name: ticket_reader
description: "FlutterKaigi 2024 Ticket Reader Application"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.6.0-216.1.beta
  flutter: ^3.26.0-0.1.pre

dependencies:
  collection: ^1.19.0
  common_data:
    path: ../../packages/common/data
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.14
  freezed_annotation: ^2.4.4
  go_router: ^14.6.0
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
