name: ticket_reader
description: "FlutterKaigi 2024 Ticket Reader Application"
publish_to: "none"
version: 0.1.0+7

environment:
  sdk: ^3.6.0-216.1.beta
  flutter: ^3.26.0-0.1.pre

dependencies:
  collection: ^1.19.0
  common_data:
    path: ../../packages/common/data
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.14
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.6.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mesh_gradient: ^1.3.8
  mobile_scanner: ^6.0.2
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.3.5
  ticket_api:
    path: ../../packages/common/ticket_api
  two_dimensional_scrollables: ^0.3.3

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  freezed: ^2.5.7
  go_router_builder: ^2.7.0
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
