name: app_features_debug
description: "This package provides debug-related features for the application."
publish_to: "none"
version: 0.0.1
homepage: "https://github.com/FlutterKaigi/2024/tree/main/packages/app/features/debug"

environment:
  sdk: ^3.6.0-216.1.beta
  flutter: ^3.26.0-0.1.pre

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.7
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.0
