default_platform(:ios)

platform :ios do
  lane :deploy_appstore do
    key_data = Base64.strict_decode64(ENV['KEY_BASE64'])
    
    app_store_connect_api_key(
      key_id: ENV['KEY_ID'],
      issuer_id: ENV['ISSUER_ID'],
      key_content: key_data,
    )

    upload_to_app_store(
      app_identifier: app_id,
      api_key: api_key,
      ipa: "../build/ios/ipa/Runner.ipa",
      skip_waiting_for_build_processing: true,
    )
  end
end
