name: app_cores_designsystem
description: "This package provides style definitions, themes, etc., for the app."
publish_to: "none"
version: 0.0.1
homepage: |
  https://github.com/FlutterKaigi/2024/tree/main/packages/app/cores/designsystem

environment:
  sdk: ^3.5.0-293.0.dev
  flutter: ^3.23.0-13.0.pre

dependencies:
  app_cores_core:
    path: ../core
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  vector_graphics: ^1.1.11+1

dev_dependencies:
  build_runner: ^2.4.11

  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.6.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12

flutter:
  assets:
    - assets/logo/

flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true
  integrations:
    flutter_svg: true
