arb-dir: assets/l10n
output-dir: lib/src/gen/l10n
template-arb-file: app_ja.arb
output-localization-file: l10n.dart
output-class: L10nSettings
synthetic-package: false
preferred-supported-locales:
  - ja
  - en
nullable-getter: false
format: true
