name: app_cores_core
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1
homepage: |
  https://github.com/FlutterKaigi/2024/tree/main/packages/app/cores/core

environment:
  sdk: ^3.6.0-216.1.beta
  flutter: ^3.26.0-0.1.pre

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.12

  custom_lint: ^0.6.7
  flutter_gen_runner: ^5.6.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
