name: app_cores_core
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1
homepage: |
  https://github.com/FlutterKaigi/2024/tree/main/packages/app/cores/core

environment:
  sdk: ^3.6.0-334.4.beta
  flutter: ^3.27.0-0.2.pre

dependencies:
  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  hooks_riverpod: ^2.6.1
  package_info_plus: ^8.0.0
  permission_handler: ^11.3.1
  riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.12

  custom_lint: ^0.6.7
  flutter_gen_runner: ^5.6.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
