name: ticket_web
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0-216.1.beta

dependencies:
  collection: ^1.19.0
  common_data:
    path: ../../packages/common/data
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  hooks_riverpod: ^2.5.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  slang: ^3.31.2
  slang_flutter: ^3.31.0
  theme_tailor_annotation: ^3.0.1
  ticket_api:
    path: ../../packages/common/ticket_api
  url_launcher: ^6.3.0
  vector_graphics: ^1.1.11+1

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  flutter_gen_runner: ^5.7.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.7.0
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  slang_build_runner: ^3.31.0
  theme_tailor: ^3.0.1
  vector_graphics_compiler: ^1.1.11+1

dependency_overrides:
  vector_graphics:
    git:
      url: https://github.com/YumNumm/vector_graphics.git
      ref: ae04010d19feff0db4e5b1763aa43d340fa6fa5e
      path: packages/vector_graphics
  yet_another_json_isolate:
    git:
      url: https://github.com/YumNumm/supabase-flutter.git
      ref: 4edc00b3b70621d37814b8c1fbef448655a4b222
      path: packages/yet_another_json_isolate

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/NotoSansJP/OFL.txt
    - assets/fonts/Poppins/OFL.txt
    - path: assets/images/sns/
    - path: assets/images/svg/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Regular.otf
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Bold.otf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/core/gen
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    outputs:
      directory_path_enabled: true
