name: conference_2024_website
description: "FlutterKaigi 2024 official website."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.4.0-282.3.beta
  flutter: ^3.22.0-0.3.pre

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^14.1.2
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  theme_tailor_annotation: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  theme_tailor: ^3.0.1

flutter:
  generate: true
  uses-material-design: true
