name: conference_2024_website
description: "FlutterKaigi 2024 official website."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0-191.0.dev
  flutter: ^3.23.0-9.0.pre

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  go_router: ^14.1.2
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  theme_tailor_annotation: ^3.0.1
  vector_graphics: ^1.1.11+1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  theme_tailor: ^3.0.1
  vector_graphics_compiler: ^1.1.11+1

flutter:
  uses-material-design: true

  assets:
    - path: assets/svg/
      transformers:
        - package: vector_graphics_compiler
    - assets/fonts/NotoSansJP/OFL.txt
    - assets/fonts/Poppins/OFL.txt

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Regular.otf
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Bold.otf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
