name: conference_2024_app
description: "FlutterKaigi 2024 official application."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0-191.0.dev
  flutter: ^3.23.0-9.0.pre

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
