name: conference_2024_app
description: "FlutterKaigi 2024 official application."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0-191.0.dev
  flutter: ^3.23.0-9.0.pre

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  hooks_riverpod: ^2.5.1
  packages_app_features_about:
    path: ../../packages/app/features/about
  packages_app_features_news:
    path: ../../packages/app/features/news
  packages_app_features_session:
    path: ../../packages/app/features/session
  packages_app_features_venue:
    path: ../../packages/app/features/venue
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.0
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12

flutter:
  uses-material-design: true
