name: conference_2024_app
description: "FlutterKaigi 2024 official application."
publish_to: "none"
version: 1.1.0+10

environment:
  sdk: ^3.6.0-216.1.beta
  flutter: ^3.26.0-0.1.pre

dependencies:
  accessibility_tools: ^2.2.2
  app_cores_core:
    path: ../../packages/app/cores/core
  app_cores_designsystem:
    path: ../../packages/app/cores/designsystem
  app_cores_settings:
    path: ../../packages/app/cores/settings
  app_features_about:
    path: ../../packages/app/features/about
  app_features_debug:
    path: ../../packages/app/features/debug
  app_features_news:
    path: ../../packages/app/features/news
  app_features_session:
    path: ../../packages/app/features/session
  app_features_venue:
    path: ../../packages/app/features/venue
  common_data:
    path: ../../packages/common/data
  dynamic_color: ^1.7.0
  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.7
  hooks_riverpod: ^2.6.1
  intl: ^0.19.0
  permission_handler: ^11.3.1
  pub_semver: ^2.1.4
  riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
