name: conference_2024_app
description: "FlutterKaigi 2024 official application."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0-191.0.dev
  flutter: ^3.23.0-9.0.pre

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.0

flutter:
  uses-material-design: true
