name: app_features_session
description: "This package provides session-related features for the application."
publish_to: "none"
version: 0.0.1
homepage: "https://github.com/FlutterKaigi/2024/tree/main/packages/app/features/session"

environment:
  sdk: ^3.6.0-216.1.beta
  flutter: ^3.26.0-0.1.pre

dependencies:
  add_2_calendar: ^3.0.1
  app_cores_core:
    path: ../../cores/core
  app_cores_designsystem:
    path: ../../cores/designsystem
  app_cores_settings:
    path: ../../cores/settings
  collection: ^1.19.0
  common_data:
    path: ../../../common/data
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.4+1
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.2.7
  hooks_riverpod: ^2.6.1
  intl: ^0.19.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.7.0
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
