name: Unit Test for Supabase Database

on:
  pull_request:
    paths:
      - "packages/common/data/**.sql"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      # https://github.com/supabase/setup-cli
      - name: Install supabase cli
        uses: supabase/setup-cli@3b9dbf86026385dcfd2b11263e0924d0bb4a9028 # v1.4.0

      - name: start supabase database
        working-directory: packages/common/data
        run: supabase db start

      - name: lint SQL
        working-directory: packages/common/data
        run: supabase db lint

      - name: unit test
        working-directory: packages/common/data
        run: supabase db test
