name: Unit Test for Supabase Database

on:
  pull_request:
    paths:
      - "packages/common/data/**.sql"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      # https://github.com/supabase/setup-cli
      - name: Install supabase cli
        uses: supabase/setup-cli@7c6d72a8c2fea26067db1b32c7fc301ae189f493 # v1.4.0

      - name: Set fake environment variables
        working-directory: packages/common/data
        run: |
          cp .env.example .env

      - name: start supabase database
        working-directory: packages/common/data
        run: supabase db start

      - name: lint SQL
        working-directory: packages/common/data
        run: supabase db lint

      - name: unit test
        working-directory: packages/common/data
        run: supabase db test
