name: Deploy Web on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      - name: Build Web
        working-directory: apps/website
        run: |
          flutter build web \
            --release \
            --wasm

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: website-2024-preview
          directory: apps/website/build/web
