name: Deploy App Android

on:
  workflow_dispatch:
    inputs:
      environment:
        description: environment
        required: true
        type: choice
        options:
          - "flutterkaigi-app-2024-development"
          - "flutterkaigi-app-2024-production"

permissions:
  contents: read

jobs:
  check-environment:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Check Environment
        run: |
          # flutterkaigi-app-2024-development はまだ未対応
          if [ "${{ github.event.inputs.environment }}" = "flutterkaigi-app-2024-development" ]; then
            echo "flutterkaigi-app-2024-development is not supported yet"
            exit 1
          fi

  deploy-app-android:
    needs: check-environment
    runs-on: ubuntu-22.04
    environment: ${{ github.event.inputs.environment }}
    timeout-minutes: 20

    steps:
      - run: echo "Test"
