name: Deploy API

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/ticket-api

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "api"
  cancel-in-progress: false

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      # https://github.com/cloudflare/wrangler-action
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@f84a562284fc78278ff9052435d9526f9c718361 # v3.7.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: pnpm
