name: Deploy Web on PR

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "docs/**"
      - "apps/app/**"
      - "packages/app/**"
      - "**/*.md"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      - name: Generate L10n
        working-directory: apps/website
        run: flutter gen-l10n

      - name: Build Web
        working-directory: apps/website
        run: |
          flutter build web \
            --release \
            --wasm

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: website-2024-preview
          directory: apps/website/build/web
