name: Deploy Website

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "docs/**"
      - "apps/app/**"
      - "packages/app/**"
      - "**/*.md"
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

jobs:
  build-website-flutter-web:
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      - name: Build Web
        working-directory: apps/website
        run: |
          flutter build web \
            --release \
            --wasm \
            --dart-define-from-file=defines/production.env

      - name: Upload Artifacts
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: website-flutter-web
          path: apps/website/build/web

  build-website-html-rewriter-api:
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/pnpm/action-setup
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        name: Install pnpm
        with:
          run_install: true

      - name: Build Function
        run: pnpm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: website-html-rewriter-api
          path: apis/website-html-rewriter/dist

  deploy-website:
    runs-on: ubuntu-22.04
    needs:
      - build-website-flutter-web
      - build-website-html-rewriter-api
    steps:

      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      # https://github.com/pnpm/action-setup
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        name: Install pnpm
        with:
          run_install: true

      - name: Download Artifacts (Website)
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: website-flutter-web
          path: ./artifacts-website

      - name: Download Artifacts (Website HTML Rewriter API)
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: website-html-rewriter-api
          path: ./artifacts-website-html-rewriter

      - name: Merge Artifacts
        run: |
          mkdir -p ./artifacts
          mv ./artifacts-website/* ./artifacts
          mv ./artifacts-website-html-rewriter/* ./artifacts
          mv ./artifacts apis/website-html-rewriter/dist

      - name: Deploy to Cloudflare Pages
        working-directory: apis/website-html-rewriter
        run: pnpm install && pnpm run upload
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
