name: Deploy Website

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "docs/**"
      - "apps/app/**"
      - "packages/app/**"
      - "**/*.md"
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

jobs:
  deploy-website:
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      - name: Build Web
        working-directory: apps/website
        run: |
          flutter build web \
            --release \
            --wasm \
            --dart-define-from-file=defines/production.env

      # https://github.com/cloudflare/pages-action
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: flutterkaigi-2024
          directory: apps/website/build/web
