name: Deploy Web to Github pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      - name: Build Web
        working-directory: apps/website
        run: |
          flutter build web \
            --release \
            --wasm \
            --base-href "/2024/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/website/build/web
          name: web

  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
