name: Deploy Ticket

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "docs/**"
      - "apps/app/**"
      - "apps/website/**"
      - "packages/app/**"
      - "**/*.md"
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      - name: Build Web (Production)
        id: build-web-production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: apps/ticket_web
        run: |
          flutter build web \
            --release \
            --wasm \
            --dart-define-from-file=defines/production.env

      - name: Build Web (Staging)
        if: github.event_name == 'pull_request'
        working-directory: apps/ticket_web
        run: |
          flutter build web \
            --release \
            --wasm \
            --dart-define-from-file=defines/staging.env

      # https://github.com/cloudflare/pages-action
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: flutterkaigi-ticket-2024
          directory: apps/ticket_web/build/web
