name: "Issue Labeler"
on:
  issues:
    types:
      - opened

permissions:
  contents: read
  issues: write

jobs:
  labeler-issue:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    strategy:
      matrix:
        template:
          - task_for_contributor.yaml
          - task_for_staff.yaml

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/stefanbuck/github-issue-parser
      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@2d2ff50d4aae06ab58d26bf59468d98086605f11 # v3.2.1
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/${{ matrix.template }}

      # https://github.com/redhat-plumbers-in-action/advanced-issue-labeler
      - name: Set labels based on severity field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@39087a4b30cb98d57f25f34d617a6af8163c17d9 # v3.2.1
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          template: ${{ matrix.template }}
          config-path: .github/labeler-issue.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
