name: Check Diff

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check-diff:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      # https://github.com/actions/cache
      - name: Cache build_runner
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: |
            **/.dart_tool/build
          key: build-runner-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/pubspec.lock', '**/build.yaml', '**/assets/**/*.*') }}
          restore-keys: |
            build-runner-${{ runner.os }}-${{ runner.arch }}-

      - name: Rebuild
        run: melos run rebuild --no-select

      - name: Check diff
        run: |
          git add -N .
          git diff --name-only --exit-code
