name: Check Diff

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check-diff:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      - name: Rebuild
        run: melos run rebuild --no-select

      - name: Check diff
        run: |
          git add -N .
          git diff --name-only --exit-code
