name: Check Changes

on:
  workflow_call:
    outputs:
      any:
        value: ${{ jobs.changes.outputs.any }}
      database:
        value: ${{ jobs.changes.outputs.database }}
      diff:
        value: ${{ jobs.changes.outputs.diff }}
      markdownlint:
        value: ${{ jobs.changes.outputs.markdownlint }}
      prettier:
        value: ${{ jobs.changes.outputs.prettier }}
      sql-format:
        value: ${{ jobs.changes.outputs.sql-format }}
      textlint:
        value: ${{ jobs.changes.outputs.textlint }}

permissions:
  contents: read
  pull-requests: read

jobs:
  changes:
    runs-on: ubuntu-22.04
    outputs:
      any: ${{ steps.filter.outputs.changes != '[]' }}
      database: ${{ steps.filter.outputs.database }}
      diff: ${{ steps.filter.outputs.diff }}
      markdownlint: ${{ steps.filter.outputs.markdownlint }}
      prettier: ${{ steps.filter.outputs.prettier }}
      sql-format: ${{ steps.filter.outputs.sql-format }}
      textlint: ${{ steps.filter.outputs.textlint }}
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      # https://github.com/marketplace/actions/paths-changes-filter
      - name: Paths Changes Filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            database:
              - "packages/common/data/**.sql"
            diff:
              - "**.dart"
              - "**.yaml"
              - "**.pubspec.lock"
            markdownlint:
              - "**.md"
            prettier:
              - "**.json"
              - "**.jsonc"
              - "**.yaml"
            sql-format:
              - "packages/common/data/**.sql"
            textlint:
              - "**.md"
              - "apps/app/**/**.arb"
