name: Check Packages

on:
  workflow_call:

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  pull-requests: write
  statuses: write

jobs:
  check-packages:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      - name: Format
        run: melos format -c 5 --output none --set-exit-if-changed

      - name: Circular Dependency
        run: melos list --cycles

      # https://github.com/reviewdog/action-setup
      - uses: reviewdog/action-setup@3f401fe1d58fe77e10d665ab713057375e39b887 # v1.3.0

      - name: Analyze
        id: analyze
        continue-on-error: true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dart analyze 2>/dev/null | \
            sed 's/^[[:space:]]*//' | \
            grep -E '^(info|warning|error)' | \
            reviewdog \
              -efm="%t%[a-z]%+ - %f:%l:%c - %m - %s" \
              -name="dart analyze" \
              -reporter=github-pr-review \
              -level=info \
              -fail-level=any \
              -tee

      - name: Custom Lint
        id: custom-lint
        continue-on-error: true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dart run custom_lint 2>/dev/null | \
            grep -E '(INFO|WARN|ERROR)$' | \
            sed 's/^[[:space:]]*//' | \
            reviewdog \
              -efm="%f:%l:%c • %m • %s • %t%[A-Z]%+" \
              -name="dart run custom_lint" \
              -reporter=github-pr-review \
              -level=info \
              -fail-level=any \
              -tee

      - name: Status Check
        if: steps.analyze.outcome == 'failure' || steps.custom-lint.outcome == 'failure'
        run: exit 1
